export function clg_lists() {
    return [  
    {"Name" : "Government Science College Jhalod"},
    {"Name" : "I. V. Patel College of Commerce Nadiad"},
    {"Name" :"P. D. Pandya Mahila Commerce College Ghodasar"},
	{"Name" : "A & M Institute of Computer & Technology	Pathankot"},
	{"Name":"A & M Institute of Management & Technology Pathankot"},
	{"Name":"A R M College of Engineering and Technology	Maraimalai Nagar"},
	{"Name":"A. C. Patil College of Engineering	Navi Mumbai"},
	{"Name":"A. G. Teachers College Navrangpura"},
	{"Name":"A. G. Unani Medical College"},
	{"Name": "A. K. T. Memorial College of Engineering & Technology"},	
	{"Name": "A. L. T. Training College"},
	{"Name" : "A. L. T. Training Colleg"},
	{"Name" : "A. M. College of Science, Management & Computer Technology (AMCOST)"},
	{"Name" : "A. N. Shiksha Shastri Mahavidyalaya"},
	{"Name" :"A. P. S. Mahavidhyalaya"},	
	{"Name" :"A. S. Institute of Business Administration"},	
	{"Name" :"A. S. Institute of Information Technology"},	
	{"Name" :"A. S. Institute of Professional Studies"},
	{"Name":"A.C.T. College of Engineering and TechnologyMadurantakam"},
	{"Name" :"A.R. Engineering College	Kappiyampuliyur"},
	{"Name" : "A.S. College	Khanna"},
	{"Name" :"A.S. College for Women"},
	{"Name":"A.S. College of Education"},
	{"Name":"Aadi College of Nursing"},	
	{"Name":"Aadinath Shikshak Prashikshan Mahavidyalaya"},	
	{"Name":"Aai Tuljabhavani Shikshan Prasarak Mandal's Shivashakti Saganak Mahavidyalaya"},	
	{"Name":"Aakar Adhyapan Mandir	Ognaj"},
	{"Name":"Aakash College of Education"},	
	{"Name":"Aakson Academie"},
	{"Name":"Aalim Muhammed Salegh Academy of Architecture"},	
	{"Name":"Aalim Muhammed Salegh College of Engineering"},	
	{"Name":"Aasra Institute of Advance Studies"},	
	{"Name":"Aayojan School of Architecture"},	
	{"Name":"Abasaheb Garware Institute of Management Studies"},	
	{"Name":"Abbas Khan College for Women"},	
	{"Name":"Abbnoor Institute of Information Technology"},	
	{"Name":"Abdullah Women's College"},	
	{"Name":"Abhijit Kadam Institute of Management and Social Sciences"},	
	{"Name":"Abhilasha Teacher's Training College"},	
    {"Name":"Abhilashi College of Education"},
    {"Name": "Gandhigram Rural University ,Gandhigram"},
    {"Name": "Hindustan Institute of Technology and Science,Chennai"},
    {"Name": "Indian Institute of Information Technology, Design and Manufacturing,Chennai"},
    {"Name": "Indian Institute of Technology Madras,Chennai"},
    {"Name": "Indian Maritime University,Chennai"},
    {"Name": "Kalasalingam University,Krishnankoil"},
    {"Name": "Karpagam Academy of Higher Education	Coimbatore"},
    {"Name": "Karunya Institute of Technology and Sciences	Coimbatore"},
    {"Name": "Madurai Kamaraj University	Madurai"},
    {"Name": "Manonmaniam Sundaranar University	Tirunelveli"},
    {"Name": "Meenakshi Academy of Higher Education and Research	Chennai"},
    {"Name": "Mother Teresa Women's University	Kodaikanal"},
    {"Name": "National Institute of Technology, Tiruchirappalli	Tiruchirappalli"},
    {"Name": "Periyar Maniammai Institute of Science and Technology"},
    {"Name": "Periyar University"},
    {"Name": "Ponnaiyan Ramajayam Institute of Science and Technology,Thanjavur"},
    {"Name": "Rajiv Gandhi National Institute of Youth Development	Sriperumbudur"},
    {"Name": "SASTRA University,Thanjavur"},
    {"Name": "Sathyabama Institute of Science and Technology,Chennai"},
    {"Name": "Saveetha University,Chennai"},
    {"Name": "Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya	Kanchipuram"},
    {"Name": "Sri Ramachandra Institute of Higher Education and Research,Chennai"},
    {"Name": "SRM Institute of Science and Technology,Chennai"},
    {"Name": "St. Peter's University,Chennai"},
    {"Name": "Alagappa University,Karaikudi"},
    {"Name": "Amrita Vishwa Vidyapeetham,Coimbatore"},
    {"Name": "Anna University,Chennai"},
    {"Name": "Annamalai University,Chidambaram"},
    {"Name": "Avinashilingam University,Coimbatore"},
    {"Name": "B.S. Abdur Rahman Crescent Institute of Science and Technology,Chennai"},
    {"Name": "Bharath Institute of Higher Education and Research,Chennai"},
    {"Name": "Bharathiar University	Coimbatore"},
    {"Name": "Bharathidasan University,Tiruchirappalli"},
    {"Name": "Central University of Tamil Nadu,Thiruvarur"},
    {"Name": "Chennai Mathematical Institute,Chennai"},
    {"Name": "Dakshina Bharat Hindi Prachar Sabha,Chennai"},
    {"Name": "Dr. M.G.R. Educational and Research Institute	Chennai"},
    {"Name": "Tamil Nadu Veterinary and Animal Sciences University,Chennai"},
    {"Name": "Tamil University,Thanjavur"},
    {"Name": "Thiruvalluvar University,Vellore"},
    {"Name": "University of Madras,Chennai"},
    {"Name": "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology,chennai"},
    {"Name": "Vels University,Chennai"},
    {"Name": "Vinayaka Missions University,Salem"},
    {"Name": "VIT University,Vellore"},
    ]
}

export function renderClgLists(state, val) {
    return (
        state.Name.toLowerCase().indexOf(val.toLowerCase()) !== -1
    );
}